# -*- mode: ruby -*-
# vi: set ft=ruby :

# see also https://github.com/vagrant-libvirt/vagrant-libvirt

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
[ '/home/niklaus/.vagrant.d/boxes', '/var/lib/libvirt/images'].each do |symlink|
  unless File.symlink?(symlink)
    puts "Warning: #{symlink} is not a symlink"
  end
end

Vagrant.configure("2") do |config|
  required_plugins = %w(vagrant-libvirt vagrant-timezone)
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "bullseye"
  config.vm.provider :libvirt do |v|
    v.cpus=2
    # v.keymap = "en-us" works!
    v.keymap = "de-ch" # works
    #v.keymap = "de_ch" # fails
    # v.keymap = "sg"
    v.memory=4048
    v.default_prefix="elexis-ng"
    v.storage_pool_path = "/opt/images"
    machine_virtual_size = "101GB";
    management_network_autostart = true;
  end

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "Europe/Zurich"
    # calls timedatectl set-timezone 'Europe/Zurich'
  end
#  config.vm.network "public_network", bridge: ADAPTER #, auto_config: false
  # https://www.vagrantup.com/docs/networking/public_network#disable-auto-configuration
  # manual ip
  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  # https://www.vagrantup.com/docs/synced-folders/nfs
  config.vm.synced_folder "/opt", "/opt",
      :create => false,
      :nfs => true, 
      :nfs_version => 4,
      :nfs_export => false,
      :nfs_udp => false
#  https://stackoverflow.com/questions/22643177/ssh-onto-vagrant-box-with-different-username (answer 6)


  config.vm.provision "file", source: "../scripts/", destination: "/home/vagrant/"
  config.vm.provision "file", source: "~/.config/awesome/", destination: "/home/vagrant/.config/"
  config.vm.provision "file", source: "~/.config/fish/conf.d/", destination: "/home/vagrant/.config/fish/"
  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
  # next  files must be run in this order
  config.vm.provision "shell", path: "../scripts/setup_minimal.sh"
  config.vm.provision "shell", path: "../scripts/download_oomp_rcptt.sh"
  config.vm.provision "shell", path: "../scripts/setup_elexis.sh"
  config.vm.provision "shell", path: "../scripts/setup_jenkins_slave.sh"
  # next file is commented out, as it only good for Niklaus Giger workspace
  # config.vm.provision "shell", path: "../scripts/setup_niklaus.sh"
  # in vagrant ssh: call sudo /opt/src/elexis-uitest/vagrant/scripts/setup_minimal.sh et el
end
