# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "peru/my_windows-10-enterprise-x64-eval"
  config.vm.box_version = "20210401.01"
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network", bridge: [ "eth0", "enp3s0", "virbr0" ]
  config.vm.network "forwarded_port", guest: 3389, host: 33389 # for rdp
  # connect using: rdesktop -u vagrant -p vagrant 127.0.0.1:3389

  config.vm.synced_folder "scripts", "/test"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "8094"
    vb.cpus = 3
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
  config.vm.provision "file", source: "scripts/", destination: "$HOME"
#  config.vm.provision "shell",  path: "scripts/install_on_windows.cmd"
end
