# This workflow will build the Eclipse RCP application with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# Test it using https://rhysd.github.io/actionlint/

name: Build ElexisAllOpensource master with Maven

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "15 4 * * *"
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set locale de_CH.UTF-8
      run: |
          sudo locale-gen de_CH.UTF-8
          sudo update-locale LANG=de_CH.UTF-8
    - name: Setup timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Zurich"
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'adopt'
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with elexis-master with Maven
      run:  mvn -V clean verify -Dtycho.localArtifacts=ignore -f elexis-master/pom.xml
    - name: Upload ElexisAllOpenSourceApp (product) for linux
      uses: actions/upload-artifact@v4
      with:
        retention-days: 90
        name: Elexis-Master-linux.zip
        path: |
          elexis-master/target/products/ElexisAllOpenSourceApp-linux.gtk.x86_64.zip
    - name: Upload ElexisAllOpenSourceApp (product) for Windows
      uses: actions/upload-artifact@v4
      with:
        retention-days: 90
        name: Elexis-Master-Windows.zip
        path: |
          elexis-master/target/products/ElexisAllOpenSourceApp-win32.win32.x86_64.zip
    - name: Upload ElexisAllOpenSourceApp (product) for macosx
      uses: actions/upload-artifact@v4
      with:
        retention-days: 90
        name: Elexis-Master-macosx.zip
        path: |
          elexis-master/target/products/ElexisAllOpenSourceApp-macosx.cocoa.x86_64.tar.gz

